[package]
name = "NECspider"
version = "0.1.0"
edition = "2024"

[dependencies]
backon = "1.4.0"
bytes = "1"
indicatif = "0.17.11"
reqwest = { version = "0.12.15", default-features = true }
tokio = { version = "1.44.0", features = ["full"] }
