name: build-android

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build binary CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nttld/setup-ndk@v1.5.0
        id: setup-ndk
        with:
          ndk-version: r26d 
      - uses: Swatinem/rust-cache@v2
      - name: Build binary file
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          set +e
          cargo install cargo-ndk
          rustup target add aarch64-linux-android
          cargo ndk -t arm64-v8a -o ./jniLibs build --release
          ls -a
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android_arm64
          path: NECspider-go_arm64
