name: build-windows

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build binary CI
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Build binary file
        run: |
          cargo build --release
        continue-on-error: true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows_amd64
          path: .
