name: build

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build binary CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Build binary file
        run: |
          cargo build --release
          ls -a
        continue-on-error: true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux_amd64
          path: ./target/release/NECspider
