name: Doc

on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  Init:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Doc
      run: |
        set +e
        cargo doc -p indicatif
        ls -a
    - uses: actions/upload-artifact@v4
      with:
        name: Doc
        path: |
          target/doc/
