name: Run

on:
  workflow_dispatch:
    inputs:
      parallelism:
        required: false
        type: string
        dafault: "500"
      begin_id:
        required: true
        type: string
      end_id:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Run 
      run: cargo run -- ${{inputs.parallelism}} ${{inputs.begin_id}} ${{inputs.end_id}} > nec.log
      continue-on-error: true
    - uses: actions/upload-artifact@v4
      with:
        name: log
        path:  nec.log