name: Run

on:
  workflow_dispatch:
    inputs:
      parallelism:
        required: true
        type: string
      begin_id:
        required: true
        type: string
      end_id:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Run 
      run: cargo run -- ${{parallelism}} ${{begin_id}} ${{end_id}}
